[project]
name = "delegate-filter"
authors = ["Your Name"]
description = "A Clarity smart contract for delegated asset filtering and management"
telemetry = false
requirements = []
[contracts.delegate-filter]
path = "contracts/delegate-filter.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
